import "./globals.css";
import { Poppins } from "next/font/google";
// import { useState } from "react";

const poppins = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "NEURONPROFILE",
  description: "Generated by Mochamad Surya Rafliansyah",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const [state, setState] = useState("");

  return (
    <html
      lang="en"
      className="scroll-smooth bg-gradient-to-r from-slate-900 to-slate-950"
    >
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
          integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </head>
      <body className={poppins.className}>{children}</body>
    </html>
  );
}

